PhysicianDirectory/Models/Physician.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PhysicianDirectory.Models
{
    public class Physician
    {
        public ulong Id { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Birth Date")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime BirthDate { get; set; }
    
        [Display(Name = "Gender")]
        public string Gender { get; set; }

        [Display(Name = "Weight")]
        public int Weight { get; set; }

        [Display(Name = "Height")]
        public int Height { get; set; }
        public ContactInfo ContactInfo { get; set; }
        public Specialization Specialization { get; set; }
    }
    

}

PhysicianDirectory/Controllers/PhysicianController.cs
using PhysicianDirectory.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhysicianDirectory.Controllers
{
    public class PhysicianController : Controller
    {
        // GET: Physician
        public ActionResult PersonalInformation()
        {
            var PerInfo = from e in physicians
                          orderby e.Id
                          select e;
            return View(PerInfo);



        }
        public ActionResult ContactInformation()
        {
            var ConInfo = from e in physicians
                          orderby e.Id
                          select e;
            return View(ConInfo);



        }
        public ActionResult SpecializationInformation()
        {
            var SpecInfo = from e in physicians
                           orderby e.Id
                           select e;
            return View(SpecInfo);



        }

        public static List<Physician> physicians = new List<Physician>()
       {
           
               new Physician
            {
                Id = 1, FirstName = "Kristhel", MiddleName = "Comin", LastName="Domingo", BirthDate= DateTime.Now, Gender="Male", Height= 171, Weight= 65,
                ContactInfo = new ContactInfo {Id = 1, HomeAddress= "Address", HomePhone = 099999, OfficeAddress="Office Address", OfficePhone= 0999, CellphoneNumber=0999, EmailAdd= "michael.dionglay@pointwest.com.ph"  }
                , Specialization = new Specialization { Id =1, Name="Opthalmologist", Description = "Opthalmologist Description"} },

             new Physician
            {
                Id = 2, FirstName = "Michael", MiddleName = "Marasigan", LastName="Dionglay", BirthDate= DateTime.Now, Gender="Male", Height= 171, Weight= 65,
                ContactInfo = new ContactInfo {Id = 2, HomeAddress= "Address", HomePhone = 099999, OfficeAddress="Office Address", OfficePhone= 0999, CellphoneNumber=0999, EmailAdd= "michael.dionglay@pointwest.com.ph"  }
                , Specialization = new Specialization { Id =2, Name="Opthalmologist", Description = "Opthalmologist Description"} },

             new Physician
            {
                Id = 3, FirstName = "Diana", MiddleName = "Reyes", LastName="Rosaroso", BirthDate= DateTime.Now, Gender="Male", Height= 171, Weight= 65,
                ContactInfo = new ContactInfo {Id = 3, HomeAddress= "Address", HomePhone = 09999, OfficeAddress="Office Address", OfficePhone= 0999, CellphoneNumber=0999, EmailAdd= "michael.dionglay@pointwest.com.ph"  }
                , Specialization = new Specialization { Id =3, Name="Opthalmologist", Description = "Opthalmologist Description"} }


           
       };
      


// GET: Employee/Edit/
public ActionResult Edit(ulong ID)
        {
            

            var per = physicians.Where(p => p.Id == ID).FirstOrDefault();
            return View(per);
            
        }
        [HttpPost]
        public ActionResult Edit(ulong ID, FormCollection collection)
        {
            try
            {
                var phy = physicians.Single(p => p.Id == ID);
                if (TryUpdateModel(phy))
                {
                    
                    return RedirectToAction("PersonalInformation");
                }
                return View(phy);
            }
            catch
            {
                return View();
            }
            
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }
        static Physician input = new Physician();
        static ContactInfo contact = new ContactInfo();
        static Specialization special = new Specialization();
        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection, string next)
        {
            try
            {
                if (next != null)
                {
                    if (ModelState.IsValid)
                    {
                        if (physicians.Count > 0)
                        {
                            input.Id = physicians.Last().Id + 1;
                        }

                        else
                        {
                            input.Id = 1;
                        }

                        input.FirstName = collection["FirstName"];
                        input.MiddleName = collection["MiddleName"];
                        input.LastName = collection["LastName"];
                        DateTime BirthDate;
                        DateTime.TryParse(collection["BirthDate"], out BirthDate);
                        input.BirthDate = BirthDate;
                        
                        input.Gender = collection["Gender"];
                        string Height = collection["Height"];
                        input.Height = Int32.Parse(Height);
                        string Weight = collection["Weight"];
                        input.Weight = Int32.Parse(Weight);
                        
                        return RedirectToAction("Create1");

                    }

                }
                return View();
                    
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Create1()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create1(FormCollection collection, string next)
        {
            try
            {
                if (next != null)
                {
                    if (ModelState.IsValid)
                    {
                        
                        contact.HomeAddress = collection["HomeAddress"];
                        string HomePhone = collection["HomePhone"];
                        contact.HomePhone = ulong.Parse(HomePhone);
                        contact.OfficeAddress = collection["OfficeAddress"];
                        string OfficePhone = collection["OfficePhone"];
                        contact.OfficePhone = ulong.Parse(OfficePhone);
                        contact.EmailAdd = collection["EmailAdd"];
                       
                        return RedirectToAction("Create2");
                        //
                    }
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Create2()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create2(FormCollection collection, string next)
        {
            try
            {
                
                special.Name = collection["Name"];
                special.Description = collection["Description"];
                Physician phys = new Physician();

                phys.Id = input.Id;
                phys.FirstName = input.FirstName;
                phys.MiddleName = input.MiddleName;
                phys.LastName = input.LastName;
                phys.BirthDate = input.BirthDate;
                phys.Gender = input.Gender;
                phys.Height = input.Height;
                phys.Weight = input.Weight;

                phys.ContactInfo = new ContactInfo
                {
                    Id = input.Id,
                    HomeAddress = contact.HomeAddress,
                    HomePhone = contact.HomePhone,
                    OfficeAddress = contact.OfficeAddress,
                    OfficePhone = contact.OfficePhone,
                    EmailAdd = contact.EmailAdd,
                    CellphoneNumber = contact.CellphoneNumber
                };
                phys.Specialization = new Specialization
                {
                    Id = input.Id,
                    Name = special.Name,
                    Description = special.Description
                };
                physicians.Add(phys);
                ViewBag.result = "Record Inserted Successfully!";
                return RedirectToAction("PersonalInformation");
                
            }
              
            catch
            {
                return View();
            }
        }
       
        // GET: Employee/Delete/5
        public ActionResult Delete(ulong ID)
        {
            var del = physicians.Where(p => p.Id == ID).FirstOrDefault();
            return View(del);
        }

        // POST: Employee/Delete/5
        [HttpPost]
        public ActionResult Delete(ulong ID, FormCollection collection)
        {
            try
            {
                var per = physicians.FirstOrDefault(p => p.Id == ID);
                
                physicians.Remove(per);
                
                return RedirectToAction("PersonalInformation");
            }
            
            catch
            {
                return View();
            }
        }

    }

}

PhysicianDirectory/Views/Physician/ContactInformation.cshtml
@model IEnumerable<PhysicianDirectory.Models.Physician>

@{
    ViewBag.Title = "ContactInformation";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/viewList.css")
<h2>ContactInformation</h2>

<p>
    <a href="/Physician/Create" class="btn btn-default" name="Add Physician" style="float: right;">Add Physician</a>
</p>
<br />
<br />
<p>
    <div class="icon-bar">

        <a href="/Physician/PersonalInformation">Personal Information</a>
        <a class="active" href="/Physician/ContactInformation">Contact Information</a>
        <a href="/Physician/SpecializationInformation">Specialization</a>

    </div>

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ContactInfo.HomeAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactInfo.HomePhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactInfo.OfficeAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactInfo.OfficePhone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactInfo.EmailAdd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ContactInfo.CellphoneNumber)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ContactInfo.HomeAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactInfo.HomePhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactInfo.OfficeAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactInfo.OfficePhone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactInfo.EmailAdd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ContactInfo.CellphoneNumber)
        </td>
        
        
    </tr>
}

</table>

PhysicianDirectory/Views/Physician/Create.cshtml
@model PhysicianDirectory.Models.Physician
@Styles.Render("~/Content/viewList.css")

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";

}





    @using (Html.BeginForm("Create", "Physician", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <h2>create</h2>
        <h2>Personal Information</h2>
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control", @placeholder = "yyyy/mm/dd" } })
                    @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
                   
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                @Html.DropDownListFor(model => model.Gender, new SelectList(new[]{"Male","Female"}), new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control", @placeholder = "kg" } })
                    @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control", @placeholder = "cm" } })
                    @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                   
                    <input type="submit" value="Next" class="btn btn-default" name="next"  onclick = "return confirm('Are you sure you want to proceed to the next page?');"/>
                </div>
            </div>
        </div>
   

    }

<div>
    @Html.ActionLink("Back to List", "PersonalInformation",null, new { @class = "linkDesign" })
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhysicianDirectory/Views/Physician/Create1.cshtml
@model PhysicianDirectory.Models.ContactInfo
@Styles.Render("~/Content/viewList.css")
@{
    ViewBag.Title = "Create1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create1</h2>

@using (Html.BeginForm("Create1", "Physician", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <h2>Contact Information</h2>
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.HomeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HomePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HomePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OfficeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OfficeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OfficeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OfficePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OfficePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OfficePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAdd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAdd, new { htmlAttributes = new { @class = "form-control", @placeholder = "email@site.com" } })
                @Html.ValidationMessageFor(model => model.EmailAdd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CellphoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CellphoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CellphoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                
                <input type="submit" value="Next" class="btn btn-default" name="next" onclick = "return confirm('Are you sure you want to proceed to the next page?');"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PersonalInformation", null, new { @class = "linkDesign" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhysicianDirectory/Views/Physician/Create2.cshtml
@model PhysicianDirectory.Models.Specialization
@Styles.Render("~/Content/viewList.css")
@{
    ViewBag.Title = "Create2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create2</h2>

@using (Html.BeginForm("Create2", "Physician", FormMethod.Post))
{
    @Html.AntiForgeryToken()
   
    <h2>Specialization</h2>
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                
            </div>
        </div>
    </div>
   
    
    
}
<p>@ViewBag.result<p />
<div>
    @Html.ActionLink("Back to List", "PersonalInformation", null, new { @class = "linkDesign" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhysicianDirectory/Views/Physician/Delete.cshtml
@model PhysicianDirectory.Models.Physician

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h2>Are you sure you want to delete record of this Physician?</h2>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MiddleName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MiddleName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "PersonalInformation")
        </div>
    }
</div>

PhysicianDirectory/Views/Physician/Edit.cshtml
@model PhysicianDirectory.Models.Physician

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h3>Personal Information</h3>
        
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MiddleName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MiddleName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MiddleName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>
        <h3>Contact Information</h3>
       
        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.HomeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.HomeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.HomeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.HomePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.HomePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.HomePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.OfficeAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.OfficeAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.OfficeAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.OfficePhone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.OfficePhone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.OfficePhone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.CellphoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.CellphoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.CellphoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactInfo.EmailAdd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactInfo.EmailAdd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactInfo.EmailAdd, "", new { @class = "text-danger" })
            </div>
        </div>
        <h3>Specialization</h3>
       
        <div class="form-group">
            @Html.LabelFor(model => model.Specialization.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Specialization.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Specialization.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Specialization.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Specialization.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Specialization.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PersonalInformation")
</div>